---
version: "3"
services:
 devopsdb:
   image: sunayanrajgupta/dockerproject:dbimg-${BUILD_NUMBER}
   ports:
     - "3306:3306"

 application:
   image: sunayanrajgupta/dockerproject:appimg-${BUILD_NUMBER}
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
